Fix resolving of optional values
pickware/SwiftyJSON pull request #3
Opened 2022-07-26 13:33 UTC by svenmuennich

In #2 I add changed the way how JSON values are resolved upon initialization. This introduced a small regression for an edge case when a `JSON` value was initialized from a _literal_ containing an optional value that is actually `nil`:
```swift
let nilString: String? = nil
let json = JSON(nilString as Any)
```
In this case the value has an actual type of `String?`, even though it is cast to `Any`. This surprisingly does not match `nil` when resolving the value, resulting in a `content` of `.unknown` rather than `.null`.

This PR fixes that by resolving all values of an `Optional` type to `.null` as a fallback.

2022-07-26 20:12 UTC, svenmuennich commented on Source/SwiftyJSON/SwiftyJSON.swift
> +            return number.isBool ? .bool(number.boolValue) : .number(number)
```suggestion
        return number.isBool ? .bool(number.boolValue) : .number(number)
```

2022-07-27 09:34 UTC, florianrhein requested changes

2022-07-27 09:34 UTC, florianrhein commented on Source/SwiftyJSON/SwiftyJSON.swift
> +    case is AnyOptional:
This would match any optional which is not previously matched, even if it's not `nil`

2022-07-27 09:52 UTC, florianrhein approved these changes
Nice!

2022-07-27 09:52 UTC, merged